package pt.ipleiria.tripPlanner.gui.TripPlanner;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import pt.ipleiria.tripPlanner.gui.Models.DadosAplicacao;
import pt.ipleiria.tripPlanner.gui.Models.Participante;
import pt.ipleiria.tripPlanner.gui.events.LoginEfetuadoEvent;
import pt.ipleiria.tripPlanner.gui.events.LoginEfetuadoListener;
import pt.ipleiria.tripPlanner.gui.events.PrimeiroLoginEfetuadoEvent;
import pt.ipleiria.tripPlanner.gui.events.PrimeiroLoginEfetuadoListener;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ricardo
 */
public class Login extends javax.swing.JPanel {

    private List<LoginEfetuadoListener> loginEfetuadoListener;
    private List<PrimeiroLoginEfetuadoListener> primeiroLoginEfetuadoListener;
    private int conta = 0;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        this.loginEfetuadoListener = new ArrayList<>();
        this.primeiroLoginEfetuadoListener = new ArrayList<>();
    }

    public synchronized void addLoginEfetuadoListener(LoginEfetuadoListener listener) {
        this.loginEfetuadoListener.add(listener);
    }

    public synchronized void removeLoginEfetuadoListener(LoginEfetuadoListener listener) {
        this.loginEfetuadoListener.remove(listener);
    }

    protected synchronized void fireLoginEfetuadoEvent() {
        for (LoginEfetuadoListener listener : this.loginEfetuadoListener) {
            LoginEfetuadoEvent evento = new LoginEfetuadoEvent(this);
            listener.loginEfetuado(evento);
        }
    }

    public synchronized void addPrimeiroLoginEfetuadoListener(PrimeiroLoginEfetuadoListener listener) {
        this.primeiroLoginEfetuadoListener.add(listener);
    }

    public synchronized void removePrimeiroLoginEfetuadoListener(PrimeiroLoginEfetuadoListener listener) {
        this.primeiroLoginEfetuadoListener.remove(listener);
    }

    protected synchronized void firePrimeiroLoginEfetuadoEvent(Participante participante) {
        for (PrimeiroLoginEfetuadoListener listener : this.primeiroLoginEfetuadoListener) {
            PrimeiroLoginEfetuadoEvent evento = new PrimeiroLoginEfetuadoEvent(this, participante);
            listener.primeiroLoginEfetuado(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        lblTripPlanner = new javax.swing.JLabel();
        lblErros = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(null);

        lbUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbUsername.setText("Username:");
        add(lbUsername);
        lbUsername.setBounds(178, 210, 67, 20);

        lbPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbPassword.setText("Password:");
        add(lbPassword);
        lbPassword.setBounds(178, 250, 61, 20);

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(290, 324, 65, 25);

        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterPressed(evt);
            }
        });
        add(tfUsername);
        tfUsername.setBounds(249, 211, 196, 20);

        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterPressed(evt);
            }
        });
        add(pfPassword);
        pfPassword.setBounds(249, 251, 196, 20);

        lblTripPlanner.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        lblTripPlanner.setText("Trip Planner");
        add(lblTripPlanner);
        lblTripPlanner.setBounds(236, 141, 186, 42);

        lblErros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblErros);
        lblErros.setBounds(194, 282, 267, 16);

        jLabel1.setText("Se este é o seu primeiro acesso use o Bi como username e data de nascimento como password.");
        add(jLabel1);
        jLabel1.setBounds(122, 304, 456, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/Ride-in-Israel_Bike-riders_edited.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 968, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        confirmaLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void EnterPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_EnterPressed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblTripPlanner;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

    public void confirmaLogin() {
        lblErros.setText("");
        lblErros.setForeground(Color.red);
        if (pfPassword.getPassword().length <= 0 && tfUsername.getText().isEmpty()) {
            lblErros.setText("Introduza as credênciais!");
        } else {
            if (pfPassword.getPassword().length <= 0) {
                lblErros.setText("Não introduziu a palavra-passe!");
            } else {
                if (tfUsername.getText().isEmpty()) {
                    lblErros.setText("Não introduziu o username!");
                } else {
                    for (Participante participante : DadosAplicacao.getInstance().getParticipantes()) {
                        if (tfUsername.getText().equals(participante.getUsername())
                                && new String(pfPassword.getPassword()).equals(new String(participante.getPassword())) && !participante.isPrimeiroLogin()) {
                            DadosAplicacao.getInstance().setLogado(participante);
                            fireLoginEfetuadoEvent();
                            mudarNome();
                        } else if (participante.isPrimeiroLogin()) {
                            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

                            String dataNasc = formatter.format(participante.getDataNasc().getTime());
                            if (tfUsername.getText().equals(participante.getBI() + "") && new String(pfPassword.getPassword()).equals(dataNasc) && participante.isPrimeiroLogin()) {
                                mudarNome();
                                firePrimeiroLoginEfetuadoEvent(participante);

                            } else {
//                                if (conta < 4) {
                                lblErros.setText("Username ou Password errada.");// Tem mais " + (3 - conta + 1) + " tentativa(s)!");
//                                    conta++;
//                                } else {
//                                    System.exit(0);
//                                }
                            }
                        } else if (tfUsername.getText().equals(participante.getUsername())
                                && !new String(pfPassword.getPassword()).equals(new String(participante.getPassword()))) {
//                            if (conta < 4) {
                            lblErros.setText("Username ou Password errada.");// Tem mais " + (3 - conta + 1) + " tentativa(s)!");
//                                conta++;
//                            } else {
//                                System.exit(0);
//                            }
                        }
                    }
                }
            }
        }
    }

    public void mudarNome() {
        tfUsername.setText("");
        pfPassword.setText("");
    }
}
