package pt.ipleiria.tripPlanner.gui.participantes;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
import pt.ipleiria.tripPlanner.gui.Models.DadosAplicacao;
import pt.ipleiria.tripPlanner.gui.Models.Participante;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoListener;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ricardo
 */
public class InserirEditarParticipante extends javax.swing.JPanel {

    private List<ConfirmarClicadoListener> confirmarClicadoListener;
//    private DefaultListModel<String> modelPermissoesUtilizador;
//    private DefaultListModel<String> modelPermissoes;
//    private ArrayList<String> permissoesUtilizador;
    private Participante participante;

    /**
     * Creates new form InserirParticipante
     */
    public InserirEditarParticipante() {
        initComponents();

        this.confirmarClicadoListener = new ArrayList<>();
//        this.modelPermissoesUtilizador = new DefaultListModel<>();
//        this.modelPermissoes = new DefaultListModel<String>();
//        modelPermissoes.addElement("Localidades");
//        modelPermissoes.addElement("Viagens");
//        modelPermissoes.addElement("Etapas");
//        modelPermissoes.addElement("Alojamentos");
//        modelPermissoes.addElement("Participantes");
//        permissoesUtilizador = new ArrayList<>();

//        lstPermissoes.setModel(modelPermissoes);

    }

    public synchronized void addConfirmarClicadoListener(ConfirmarClicadoListener listener) {
        this.confirmarClicadoListener.add(listener);
    }

    public synchronized void removeConfirmarClicadoListener(ConfirmarClicadoListener listener) {
        this.confirmarClicadoListener.remove(listener);
    }

    protected synchronized void fireConfirmarClicadoEvent() {
        for (ConfirmarClicadoListener listener : this.confirmarClicadoListener) {
            ConfirmarClicadoEvent evento = new ConfirmarClicadoEvent(this);
            listener.confirmarClicado(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLocalidade = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblBI = new javax.swing.JLabel();
        tfLocalidade = new javax.swing.JTextField();
        tfBilheteIdentidade = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lblNome = new javax.swing.JLabel();
        cbICF = new javax.swing.JComboBox();
        lblCondicaoFisica = new javax.swing.JLabel();
        lblErros1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        btnOk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnOk.setText("Criar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel2.setText("Inserir/Editar Participante");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais"));

        lblLocalidade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblLocalidade.setText("*Localidade:");

        lblDataNascimento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDataNascimento.setText("*Data de Nascimento:");

        lblBI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBI.setText("*Bilhete Identidade:");

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome.setText("*Nome:");

        cbICF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Condição física...", "1", "2", "3", "4", "5" }));

        lblCondicaoFisica.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCondicaoFisica.setText("*Indice Condicao Fisica:");

        lblErros1.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLocalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfLocalidade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblBI)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfBilheteIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCondicaoFisica)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbICF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblErros1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataNascimento)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBI)
                    .addComponent(tfBilheteIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidade)
                    .addComponent(tfLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCondicaoFisica)
                    .addComponent(cbICF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblErros1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOk)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed


        if (tfNome.getText().isEmpty()) {
            lblErros1.setText("Introduza um nome!");
            return;
        }

        if (jDateChooser2 == null) {
            lblErros1.setText("Introduza uma Data de Nascimento!");
            return;
        }

        if (tfBilheteIdentidade.getText().isEmpty()) {
            lblErros1.setText("Introduza um BI!");
            return;
        } else {
            if (tfBilheteIdentidade.getText().length() != 8) {
                lblErros1.setText("BI inválido!");
                return;
            }
        }

        if (participante == null) {
            for (Participante participante1 : DadosAplicacao.getInstance().getParticipantes()) {
                if (tfBilheteIdentidade.getText().equals(participante1.getBI() + "")) {
                    lblErros1.setText("BI já existente!");
                    return;
                }
            }
        }

        if (tfLocalidade.getText().isEmpty()) {
            lblErros1.setText("Insira uma Localidade!");
            return;
        }

        if (cbICF.getSelectedIndex() < 1) {
            lblErros1.setText("Escolha um ICF");
            return;
        }


        //boolean editor = false;

//        if (cbEditor.isSelected()) {
//            if (lstPermissoesUtilizador.getModel().getSize() < 0) {
//                lblEditorErro.setText("Escolha pelo menos uma permissão de editor!");
//                return;
//            }
//            editor = true;
//        }
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dataNasc = formatter.format(jDateChooser2.getCalendar().getTime());

        Participante part;

//        for (int i = 0; i < lstPermissoesUtilizador.getModel().getSize(); i++) {
//            String permissaoUtilizador = (String) lstPermissoesUtilizador.getModel().getElementAt(i);
//            permissoesUtilizador.add(permissaoUtilizador);
//        }

        part = new Participante(tfNome.getText(), jDateChooser2.getCalendar(), Integer.parseInt(tfBilheteIdentidade.getText()), tfLocalidade.getText(), Integer.parseInt(cbICF.getModel().getElementAt(cbICF.getSelectedIndex()).toString()), false, tfBilheteIdentidade.getText(), dataNasc.toCharArray(), true);
        

        if (participante == null) {
            DadosAplicacao.getInstance().adicionarParticipante(part);
            JOptionPane.showMessageDialog(this, "Utilizador Inserido!");
        } else {
            DadosAplicacao.getInstance().atualizarParticipante(part);
            JOptionPane.showMessageDialog(this, "Utilizador Alterado!");
        }

        this.fireConfirmarClicadoEvent();


    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        this.fireConfirmarClicadoEvent();

    }//GEN-LAST:event_btnCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cbICF;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBI;
    private javax.swing.JLabel lblCondicaoFisica;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblErros1;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField tfBilheteIdentidade;
    private javax.swing.JTextField tfLocalidade;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    public void setTitulo(String string) {
        jLabel2.setText(string);
    }

    private void preencherCampos(Participante participante) {
        tfBilheteIdentidade.setText(participante.getBI() + "");
        tfLocalidade.setText(participante.getLocalidade());
        tfNome.setText(participante.getNome());
        cbICF.setSelectedIndex(participante.getICF());

//        if (participante.isEditor()) {
//            if (participante.getPermissoes() != null) {
//                for (String string : participante.getPermissoes()) {
//                    modelPermissoesUtilizador.addElement(string);
//                }
//                lstPermissoesUtilizador.setModel(modelPermissoesUtilizador);
//            }
//        }

        jDateChooser2.setCalendar(participante.getDataNasc());

    }

    public void limparCampos() {
        tfBilheteIdentidade.setText("");
        tfLocalidade.setText("");
        tfNome.setText("");
        cbICF.setSelectedIndex(0);
        //lstPermissoes.removeAll();
        jDateChooser2.setCalendar(null);
        lblErros1.setText("");
        //cbEditor.setSelected(false);
    }

    public void setParticipante(Participante participante) {
        this.participante = participante;
        btnOk.setText("Criar");
        tfBilheteIdentidade.setEnabled(true);
        if (participante != null) {
            preencherCampos(participante);
            btnOk.setText("Editar");
            tfBilheteIdentidade.setEnabled(false);
        }
    }
}
